Improved transactions
EotvosCollegium/mars pull request #143
Opened 2022-10-07 21:00 UTC by kdmnk

Now, there is an option to choose payer and receiver, and check whether the transaction is in the checkout when creating transactions.

2022-10-16 17:16 UTC, machiato32 requested changes
Add emails for every transaction. 🙂

2022-10-16 17:16 UTC, machiato32 commented on resources/views/utils/checkout/add-transaction.blade.php
> +            @endcan
A gazdasági alelnöknek a szöveghez még: "A lenti átvevő mezőnél válaszd ki azt a személyt, akinek odaadod a kasszából /zsebedből kivett pénzt. Hogyha te intézted a vásárlást, akkor magadat válaszd ki.\nA jobb oldali mezőt akkor pipáld ki, hogyha nem zsebből fizetted ki az összeget, hanem a kasszából kivetted a pénzt."

2022-10-16 17:16 UTC, machiato32 commented on resources/views/utils/checkout/add-transaction.blade.php
> +                <x-input.checkbox m=6 l=6 id="in_checkout" checked text="checkout.in_checkout_descr"/>
Description: "Az összeg a kasszából került kifizetésre"

2022-10-16 17:16 UTC, machiato32 commented on resources/views/utils/checkout/my_transactions.blade.php
> +                <blockquote>@lang('checkout.depts_descr')</blockquote>
"Ennyivel tartozol a kassza felé / tartozik neked a kassza. Keresd fel a kassza felelősét!\n(Pozitív összeg esetén te tartozol, negatív esetén a kassza)"

2022-10-16 17:16 UTC, machiato32 commented on resources/views/utils/checkout/list.blade.php
> +    @else
Add <th> tags with the names of the columns

2022-10-18 12:12 UTC, kdmnk commented
@machiato32 Please check the emails.

2022-10-20 21:52 UTC, machiato32 commented
Made some changes:
- fixed missing assigning of the `title` variable of the Transactions mailable
- added `paid_at `to the fillable array in the Transaction model
- better readability in emails: hungarian language, no - sign at the transactions, receiver and payer not stated if same
- removed unnecessary translations from students council `checkout.app.blade`
- added more explanations for better understanding to the checkout page

2022-10-20 21:54 UTC, machiato32 approved these changes
Please test everything, especially read through the changed explanations. If it looks good to you, you can merge.

2022-10-21 09:50 UTC, merged