Allowing externs to be assigned to rooms
EotvosCollegium/mars pull request #346
Opened 2023-10-02 21:19 UTC by viktorcsimma

Closes #345. Simply allows all active collegists (including externs) to be assigned to rooms.

2023-10-02 21:21 UTC, kdmnk requested changes
Filter on collegists at least

2023-10-08 15:28 UTC, viktorcsimma commented
As I remember, only collegists can have an active status; am I wrong? I have added an additional filter anyway.

2023-10-08 16:56 UTC, kdmnk commented
True, but there is no connection in them in the database. For example, after users become alumni, they still have statuses for the old semesters. (not relevant in this case, but still)

2023-10-08 16:56 UTC, kdmnk approved these changes

2023-10-21 10:49 UTC, merged