Adding receipts to expenses
EotvosCollegium/mars pull request #356
Opened 2023-10-28 12:23 UTC by viktorcsimma

Closes #331. Receipts are required for expenses; they can also be downloaded from the list, but they cannot be modified.

2023-11-04 15:06 UTC, kdmnk commented on resources/views/utils/checkout/add-expense.blade.php
> +                <x-input.file s="12" xl="8" id="receipt" style="margin-top:auto" accept=".pdf,.jpg,.png,.jpeg,.gif"
Only one question: why xl=8? I'd just delete it.

2023-11-04 15:09 UTC, kdmnk requested changes

2023-11-04 15:09 UTC, kdmnk commented on app/Utils/CheckoutHandler.php
> +        $path = $request->file('receipt')->store('receipts');
Wrap this and the Transaction::create in a DB::transaction(...), so if either of the logic fails it backtracks. Same with deletion.

2023-11-05 09:04 UTC, viktorcsimma commented
Done:)

2023-12-18 20:42 UTC, kdmnk approved these changes
Codewise it's fine, you can test it live :P

One comment though: you can put the mail sending into the transaction as well. Now if that fails, the user gets an error message, yet the transactions are created properly. Depends how we want it.

2023-12-20 19:19 UTC, viktorcsimma commented
Hm... I have arguments both for and against it. Such a situation would be confusing; but then if anything happens with the mail function, it does not paralyse the function itself.

I think I'm going to merge it now; thank you:)

2023-12-20 19:19 UTC, merged