Updating and expanding instructions for connecting to the radius network
EotvosCollegium/mars pull request #450
Opened 2024-03-01 10:47 UTC by viktorcsimma

I've just helped someone connect to the network and for her, the only way her phone worked was by setting "Use system certificate" and the domain "wifi.eotvos.elte.hu". I've also made other changes and clarifications and included a link to the Windows guide I often use.

2024-03-01 10:52 UTC, horcsinbalint requested changes
Do not use external links

2024-03-01 10:54 UTC, viktorcsimma commented
Why not? It worked for me a lot of times; we can still update it if it breaks sometime.

2024-03-01 10:56 UTC, horcsinbalint commented
Someone might get scammed. No one likes to update because an external website seizes to operate

2024-03-01 10:58 UTC, horcsinbalint commented on resources/lang/en/internet.php
The domain name should be configurable in .env

2024-03-01 11:16 UTC, viktorcsimma commented
Well, it would be great if someone could write an internal guide for the same; otherwise, I would insist on this. I think the benefits clearly outweigh the security risks.

@kdmnk what do you think?

2024-03-01 11:40 UTC, kdmnk commented
If you say so, we can live with that. How often do you experience this specific issue? And yes maybe put that in .env

2024-03-01 11:51 UTC, viktorcsimma commented
I think there have been ca. 5 cases where I followed (or simply sent) this tutorial and it helped. There was someone who had not had access for more than a year before I did that.

But putting it into .env is a good idea; I’ll take a look at it in the evening.

2024-03-01 11:57 UTC, horcsinbalint commented
Does Windows care about it? I don't know, I usually don't work with such issues, but AFAIK if you simply forget the network and readd it, Windows does not care about what is the CA.
It is also a bit long description for the average user to follow.

2024-03-01 12:01 UTC, horcsinbalint commented
Here is a Hungarian description from IIG: https://iig.elte.hu/dstore/document/3505/2020_wifi_installwin10.pdf

2024-03-03 22:53 UTC, horcsinbalint commented
Should fix #402

2024-03-10 19:17 UTC, kdmnk commented
Can we close this as duplicate to #452?

2024-03-10 20:01 UTC, horcsinbalint commented
> Can we close this as duplicate to https://github.com/EotvosCollegium/mars/pull/452?

That was just a PR for the `internet-instructions` branch as it only contained suggestions for this PR.

2024-03-10 20:10 UTC, horcsinbalint reviewed
With the recent changes, I'm no longer blocking the PR. But please @kdmnk check on it before merging

2024-03-10 20:11 UTC, horcsinbalint approved these changes

2024-03-10 20:46 UTC, merged