Self-hosted instructions
EotvosCollegium/mars pull request #452
Opened 2024-03-02 18:08 UTC by horcsinbalint

My recommendations for #450

2024-03-02 18:28 UTC, horcsinbalint commented
TODO: move into blade so data from .env can be used and would also be more elegant

2024-03-04 12:13 UTC, kdmnk requested changes
This should still not be part of our codebase. Put a pdf file with the guide on the server and add a link with a configurable path to it.

2024-03-10 19:07 UTC, kdmnk approved these changes
Just one comment, after that you can merge

2024-03-10 19:07 UTC, kdmnk commented on routes/web.php
> +        Route::get('/help_windows11', [InternetController::class, 'helpWindows11'])->name('help_windows11');
delete if not used

2024-03-10 19:56 UTC, merged