Small template fixes
EotvosCollegium/mars pull request #455
Opened 2024-03-03 20:38 UTC by horcsinbalint

2024-03-04 12:18 UTC, kdmnk requested changes

2024-03-04 12:18 UTC, kdmnk commented on resources/views/latex/status-cert.blade.php
> +			COLLEGIUM
Now we have getters in the user model for the director and president. Since it's a blade file I guess you should be able to use dynamic names and contact details.
Also we have some email addresses in .env

2024-03-07 19:59 UTC, horcsinbalint commented on resources/views/latex/status-cert.blade.php
> +			COLLEGIUM
Thanks, I planned it in the future but it was quite easy to include them as well

2024-03-10 19:16 UTC, kdmnk requested changes
These functions can return null. Good question what's better, the suggested fix or to redirect with 404 with a custom error message.

2024-03-10 19:16 UTC, kdmnk commented on resources/views/latex/status-cert.blade.php
> +			E-mail:	{{config("mail.secretary_mail")}} • {{\App\Models\User::director()->email }}
```suggestion
			E-mail:	{{config("mail.secretary_mail")}} • {{\App\Models\User::director()?->email }}
```

2024-03-10 19:16 UTC, kdmnk commented on resources/views/latex/status-cert.blade.php
> +                {{ \App\Models\User::director()->name }}\\
```suggestion
                {{ \App\Models\User::director()?->name }}\\
```

2024-03-10 19:16 UTC, kdmnk commented on resources/views/latex/status-cert.blade.php
> +Alulírott {{ \App\Models\User::director()->name }}, az ELTE Eötvös József Collegium igazgatója, hivatalosan igazolom, hogy {{ $name }} (Neptun-kód: {{ $neptun }}) az ELTE Eötvös József Collegium tagj
```suggestion
Alulírott {{ \App\Models\User::director()?->name }}, az ELTE Eötvös József Collegium igazgatója, hivatalosan igazolom, hogy {{ $name }} (Neptun-kód: {{ $neptun }}) az ELTE Eötvös József Collegium tagja {{ $from }}. szeptemberétől.
```

2024-03-10 19:16 UTC, kdmnk commented on resources/views/latex/status-cert.blade.php
> +		\signature{ {{ \App\Models\User::president()->name }} }{elnök}{Eötvös József Collegium Választmány}
```suggestion
		\signature{ {{ \App\Models\User::president()?->name }} }{elnök}{Eötvös József Collegium Választmány}
```

2024-03-10 19:16 UTC, kdmnk commented on resources/views/latex/status-cert.blade.php
> +	\signature{ {{ \App\Models\User::director()->name }} }{igazgató}{Eötvös József Collegium}
```suggestion
	\signature{ {{ \App\Models\User::director()?->name }} }{igazgató}{Eötvös József Collegium}
```

2024-03-10 20:06 UTC, horcsinbalint commented
> These functions can return null. Good question what's better, the suggested fix or to redirect with 404 with a custom error message.

Thanks, I like the solution you proposed.

2024-03-10 20:47 UTC, kdmnk approved these changes

2024-03-10 20:50 UTC, merged