Refine bug reporting/feature requests (fixes #236)
EotvosCollegium/mars pull request #474
Opened 2024-03-17 16:36 UTC by Trigary

Change summary:

- The bug reporting feature has been moved from `HomeController` to its own class
- The feature got its own language resource files (instead of using `general.php`)
- Bug reporting has been generalized to "issue reporting", which includes bug reports and feature requests
  - Translations have been modified to reflect this change
  - A selector input has been added to the page, allowing users to select whether they are reporting a bug or a feature request
- Input validation has been added to the backend
- Missing GitHub auth tokens are now logged, allowing easy testing

Additional notes:

- The created issues only get the selected labels applied if the authorization used to make the request grants push access. Currently, that is not the case: no labels get applied due to a lack of permissions. This isn't a big deal: everything else still functions normally.

2024-03-19 09:10 UTC, kdmnk requested changes
I suggetsed some smaller changes, mainly to follow this convention: https://laravel.com/docs/11.x/controllers#actions-handled-by-resource-controllers

2024-03-19 09:10 UTC, kdmnk commented on app/Http/Controllers/ReportIssueController.php
> +        $validator->validate();
no comment needed, use $request->validate([...]).

2024-03-19 09:10 UTC, kdmnk commented on app/Http/Controllers/ReportIssueController.php
> +        $body = htmlspecialchars(stripslashes($request->input('description')), ENT_QUOTES);
make a helper function for sanitizing

2024-03-19 09:10 UTC, kdmnk commented on app/Http/Controllers/ReportIssueController.php
> +    public function index(): View
call this create

2024-03-19 09:10 UTC, kdmnk commented on app/Http/Controllers/ReportIssueController.php
> +    public function report(Request $request): View|RedirectResponse
call this store

2024-03-19 09:10 UTC, kdmnk commented on routes/web.php
> +    Route::post('/report_issue', [ReportIssueController::class, 'report'])->name('report_issue.report');
call `issues/create` and `issues` .

2024-03-19 15:08 UTC, Trigary commented on app/Http/Controllers/ReportIssueController.php
> +    public function index(): View
Are you sure? Based on the document you linked, I think it should be called `index`.

2024-03-19 15:10 UTC, Trigary commented
Thanks, I made the requested changes (except one, see the conversation).

2024-03-19 15:13 UTC, kdmnk commented on app/Http/Controllers/ReportIssueController.php
> +    public function index(): View
index is used to display a list of a resource. "create" is for the create page which sends the "store" request on submission. 
In another sense, index can stay as the ~main page of a feature. 
I'll let you decide.

2024-03-19 15:24 UTC, Trigary commented on app/Http/Controllers/ReportIssueController.php
> +    public function index(): View
I see, thanks. I renamed the method.

2024-03-28 11:14 UTC, kdmnk approved these changes

2024-03-31 19:09 UTC, merged