Improve the querypage for KKT/Netreg data, with workshop filtering
EotvosCollegium/mars pull request #523
Opened 2024-05-02 22:43 UTC by imol-ai

## Description
Implemented a similar interface to the user screen for querying the KKT/Netreg data. Users can now filter for workshops regarding the unpaid users, and also in the payment log.
## Related Issue
Closes #483 
## Changes
Changed the kktnetreg simple blade file into calling a livewire query.
Also put all the relevant strings in the relevant i18n categories.

2024-05-03 17:27 UTC, viktorcsimma requested changes
It's nice! There are some very small consistency-oriented requests; but otherwise, it was great work.

2024-05-03 17:27 UTC, viktorcsimma commented on resources/lang/en/general.php
> +    'council_wallet' => "Council's wallet",
It's usually called "checkout" in the code; it would be better to use that term. But it's true that it has only been in the code yet.

2024-05-03 17:27 UTC, viktorcsimma commented on resources/lang/en/general.php
> +    'student_council' => 'Student council',
It's really a minor thing, but I think it's spelled as "Council", with a capital C.

2024-05-03 17:27 UTC, viktorcsimma commented on resources/lang/hu/general.php
> +    'council_wallet' => 'Választmányi kassza',
Same here.

2024-05-03 17:27 UTC, viktorcsimma commented on resources/views/student-council/economic-committee/kktnetreg.blade.php
> +<a href="{{ route('economic_committee') }}" class="breadcrumb" style="cursor: pointer">@lang('general.council_wallet')</a>
Same here.

2024-05-03 20:15 UTC, imol-ai commented on resources/lang/en/general.php
> +    'council_wallet' => "Council's wallet",
So should I call the variable checkout, or the english localization?

2024-05-03 20:25 UTC, imol-ai commented
I hope that this is what you meant :)

2024-05-06 17:04 UTC, viktorcsimma commented
I think this will be OK for now:)

2024-05-06 17:34 UTC, viktorcsimma approved these changes
I've just merged an update from development but that's all. Again, thank you very much:)

2024-05-06 17:34 UTC, merged