Adding admin-registered users
EotvosCollegium/mars pull request #56
Opened 2022-06-24 14:37 UTC by viktorcsimma

Addresses #52.

2022-06-24 14:39 UTC, viktorcsimma commented
Setting roles is not yet possible; I will add that soon.
Also, could you check whether e-mail sending is functional?

2022-06-26 10:51 UTC, kdmnk requested changes

2022-06-26 10:51 UTC, kdmnk commented on resources/lang/hu/registration.php
> +    'used_email' => 'A megadott e-mail-címmel már létezik felhasználó.',
unnecessary (validator does this)

2022-06-26 10:51 UTC, kdmnk commented on app/Http/Controllers/Secretariat/RegistrationsController.php
> +        $user->password=\Hash::make(\Str::random(32));
$user = User::create(['name' => ..., ...])

2022-06-26 10:51 UTC, kdmnk commented on app/Http/Controllers/Secretariat/RegistrationsController.php
> +    {
$request->validate(RegisterController::USER_RULES*)

*without password

2022-06-26 10:51 UTC, kdmnk commented on resources/views/secretariat/user/list_users_component.blade.php
> +                        <x-input.text  id="name" type="text" required :value="config('custom.kkt')" />
remove :value fields

2022-06-26 10:51 UTC, kdmnk commented on app/Http/Controllers/Secretariat/RegistrationsController.php
> +            return redirect()->back()->with('message', __('registration.successfully_invited'));
Just redirect to `secretariat.permissions.show`, ['id' => $user->id]

2022-06-26 10:51 UTC, kdmnk commented on app/Http/Controllers/Secretariat/RegistrationsController.php
> +        $user->password=\Hash::make(\Str::random(32));
and verified => true

2022-06-26 15:38 UTC, viktorcsimma commented
I now check the username and the address; is that OK?

2022-06-29 19:32 UTC, kdmnk commented
I have added a custom mail view for this.
Thanks, I will release this

2022-06-29 19:34 UTC, kdmnk approved these changes

2022-06-29 19:34 UTC, merged