Upload files after application deadline
EotvosCollegium/mars pull request #620
Opened 2024-08-08 12:54 UTC by kdmnk

And sends email to the committee members (also if the notes are changed)

2024-08-08 13:19 UTC, horcsinbalint requested changes
I think these changes might trigger rate limiting for e-mail sending. We probably have a limit of 500 mails / 24 hours.
A better solution would be to send the same email with multiple recipients (the limit is probably 100 recipients / email via SMTP).

2024-08-08 13:35 UTC, BertalanD commented
I'm a bit conflicted about sending emails for notes, but if you see a use case for it, sure. But please clarify in the helper text that an email will be sent.

2024-08-08 19:06 UTC, kdmnk commented
> I'm a bit conflicted about sending emails for notes, but if you see a use case for it, sure. But please clarify in the helper text that an email will be sent.

True, I wanted to clarify it.
As far as I saw, the notes are not used that much, maybe to state some changes to the application and alike. For those, an email is nice but I can remove the feature.  You know better.

2024-08-08 19:11 UTC, BertalanD commented
> As far as I saw, the notes are not used that much, maybe to state some changes to the application and alike. For those, an email is nice but I can remove the feature. You know better.

Keeping it as a way to urgently notify application committee members about important changes to an application sounds good to me.

2024-08-09 09:59 UTC, kdmnk commented
I've used bcc now to send emails but I have issues testing it and I don't have more time now. Please test this on staging and fix if needed.

2024-08-09 10:54 UTC, BertalanD commented on app/Http/Controllers/Auth/AdmissionController.php
> +            Mail::bcc($application->committeeMembers())->queue(new ApplicationFileUploaded($request->get('name'), $application));
This throws an exception if `committeeMembers` is empty. Please address it post-commit.

2024-08-09 11:02 UTC, BertalanD commented on app/Http/Controllers/Auth/AdmissionController.php
> +            Mail::bcc($application->committeeMembers())->queue(new ApplicationNoteChanged(user(), $application, $oldValue));
seems like a false positive? `user()` is used above too, without problems

2024-08-09 11:05 UTC, BertalanD approved these changes
I'm ready to merge and deploy this.

@viktorcsimma do you have anything to add before I do that?

2024-08-09 11:34 UTC, merged

2024-08-09 11:54 UTC, viktorcsimma commented
I haven't checked it out thoroughly, but LGTM; thanks:)

2024-08-09 12:28 UTC, BertalanD commented
Needed this fix post-commit: https://github.com/EotvosCollegium/mars/commit/7d93901ca25222553bfd4c0758279f66664aa4f3