Reservable items (rooms and washing machines)
EotvosCollegium/mars pull request #623
Opened 2024-08-12 22:08 UTC by viktorcsimma

As in the title. It supports:
- washing machines (only one-hour slots, and at most 6 of them),
- rooms (with arbitrary intervals, even recurring, but they need to be verified by someone authorized).

Known issues:
- The timetable sometimes disappears when stepping forwards and then backwards.
- Reservable items cannot be created from the UI yet, only in the database.
- I have not written test cases yet; I would like to know what you think before proceeding with that.

2024-08-13 10:25 UTC, kdmnk requested changes
TBH I gave up reviewing after the controllers.
I'll continue later but my general thoughts are that it's too complex.
I suggest to switch the development process for new modules in the future to aim for an MVP first. For example here, without approval, conflicts, recurring reservations. And then add these later once we know the basics are working. 
Since we are working online, in general, if you are unsure what's the best way to go feel free to open a pr and discuss it when questions arise. 

I will think how can we eliminate the checks to distinguish between washing machines and rooms every time.

And some thoughts about recurring events: 
Take a look at google calendar, they don't care about conflicts. I haven't gone through your code but seems like checking for conflicts is a pain in the ***. Maybe we could just ignore them and set it as a new conflicting state that needs human intervention for some occasions.
Another idea that we can do is to have a standard week schedule that is connected to the semester and then we have one time events for every individual week. 
But ofc if your solution works you can keep it now, just make sure to document what your functions are doing in detail.

Otherwise, I've tried the UI, it is pretty neat, the table looks good, nice job. For the rooms though, I was thinking would not it be better to show only one day once, with all the possible rooms as columns? More often the use case is to find any room at a given time and with the current solution you need to check each room individually.

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservableItemController.php
> +            $items = ReservableItem::where('type', 'room')->get();
Make sure to validate it, then you can use:

$items = ReservableItem::query().
If ($request->type){
$items->where('type', $request->type)
}
$items->get()

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservableItemController.php
> +        $until = $from->copy()->addDays(6);
DIdn't you want to add this as part of the request?

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservableItemController.php
> +            'type' => Rule::in(["washing_machine", "room"]),
Store these as const in the model. Or you can already start using https://github.com/EotvosCollegium/mars/issues/388

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservableItemController.php
> +        $item->save();
You can make it a one liner:
$item->update(['out_of_order' => !$item->out_of_order])

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +    public function indexForWashingMachines()
This should be in the reservableItemController. In fact, the index there already does this without the dates (which I don't see why do you need here?).

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +                })->count();
What are you trying to check here exactly?
In my intuition, this should be that a user can't have more than x reservations in the future but I see that it's not connected to the user. 

I would make it something like this but I realised you might want something else:

$user->reservedItems(ReservableItem::WASHING_MACHINE)->count() >= ReservableItem::MAX_WASHING_RESERVATIONS

If you can make this as simple as this maybe we don't even need this separated as a private function.

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +        $conflictingReservations = ReservableItem::find($newReservation->reservable_item_id)
Use relation. $newReservation->reservableItem->...

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +                }
you can use rules like 'date|after:reserved_from|after:now'

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +                    );
I would add a new validation rule for this (https://laravel.com/docs/11.x/validation#custom-validation-rules)

just because this function is long already

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +                }
why don't you just create a new date at from xx:00:00 for a given xx:yy:zz. 
If it is clear in the UI then the backend can just ignore invalid times.

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +                if (Carbon::make($request->reserved_from)->addHour() < Carbon::now()) {
you can still use the built in after/before rules. Pass a string that represents Carbon::now()->subHour()

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +        }
just check and ignore the value when saving (to make the function simpler). Again, I assume the UI does not allow this.

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +    public const THIS_ONLY = 'this_only';
prefix these with EDIT_

2024-08-13 10:25 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +        }
same here, try to eliminate ->after() cases

2024-08-13 10:25 UTC, kdmnk commented on app/Livewire/Timetable.php
> +        return $splitBlocks;
how could we do that?

2024-08-13 10:25 UTC, kdmnk commented on app/Models/ReservationGroup.php
> +        'default_note',
I find the terminology default misleading. What about 'group_' as prefix?

2024-08-13 19:22 UTC, viktorcsimma commented on app/Http/Controllers/ReservableItemController.php
> +        $until = $from->copy()->addDays(6);
Actually, they aren't needed anymore; the Livewire element handles that.

2024-08-13 19:40 UTC, viktorcsimma commented on app/Http/Controllers/ReservableItemController.php
> +            'type' => Rule::in(["washing_machine", "room"]),
Good idea; I'll use a backed enum.

2024-08-13 19:44 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +    public function indexForWashingMachines()
I wanted it to resemble the real washing machine reservation book at the reception; this was the easiest way to manage that. Or do you have another idea?

2024-08-13 19:57 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +                })->count();
The idea is that they should not reserve more than 6 washing slots at once. So I count the number of reservations that belong to them, are for washing machines and end in the future.

2024-08-13 19:57 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +        $conflictingReservations = ReservableItem::find($newReservation->reservable_item_id)
True; I don't know why I have done it so:D

2024-08-13 20:15 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +                }
Well, it is not yet clear in the UI :sweat_smile: I should probably use a simple integer input there for the hour.

2024-08-13 21:00 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +                    );
Huh; wouldn't it just create more unnecessary code to create an entire new class for a rule only used once? But I'm trying to shorten the code with `sometimes` rules.

2024-08-15 10:24 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +    }
I see... and can I include this besides an existing rule in the array?

2024-08-15 10:26 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +                })->count();
Nice:) thanks!

2024-08-15 10:29 UTC, viktorcsimma commented on app/Models/Reservation.php
> +    }
The user is always non-null; so it will be fine this way.

2024-08-15 10:30 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +            });
Done:)

2024-08-15 10:30 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +                    ->first());
Done:)

2024-08-15 10:31 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +                ? $reservation->reserved_from->copy()->addHour()
Done:)

2024-08-15 10:31 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +    }
Done:)

2024-08-15 10:33 UTC, viktorcsimma commented on app/Models/ReservationGroup.php
> +    }
Done:)

2024-08-15 10:33 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +                ? $reservation->reserved_from->copy()->addHour()
I've forgot to rename the prefix; that was the problem.

2024-08-15 10:34 UTC, viktorcsimma commented on app/Models/ReservationGroup.php
> +    }
Done:) I've inserted a backslash.

2024-08-15 10:36 UTC, viktorcsimma commented on app/Models/ReservationGroup.php
> +}
I'll do that.

2024-08-15 10:37 UTC, viktorcsimma commented on database/migrations/2019_10_19_193746_create_workshops_table.php
> +        foreach (Workshop::ALLas $key => $workshop) {
Done:)

2024-08-15 10:37 UTC, viktorcsimma commented on database/migrations/2019_10_13_130718_create_roles_table.php
> +        foreach (Role::ALLas $key => $role) {
Done:)

2024-08-15 10:40 UTC, viktorcsimma commented on database/migrations/2019_10_19_200553_create_faculties_table.php
> +        foreach (Faculty::ALLas $key => $faculty) {
Done:)

2024-08-15 10:43 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +        }
Done:)

2024-08-15 10:44 UTC, viktorcsimma commented on resources/views/livewire/timetable.blade.php
> +                                    </div>
No, it is important to be able to use PHP variables here.

2024-08-15 10:46 UTC, viktorcsimma commented on database/factories/ReservableItemFactory.php
> +        ];
It will be fine for now.

2024-08-15 10:47 UTC, viktorcsimma commented on app/Livewire/Timetable.php
> +    }
Done:)

2024-08-15 10:49 UTC, viktorcsimma commented on app/Mail/ReportReservableItemFault.php
> +                 . ' jelentve';
It can be assumed to be read only by admins (who do speak Hungarian).

2024-08-15 10:54 UTC, viktorcsimma commented on app/Livewire/Timetable.php
> +        return $splitBlocks;
I've now put the splitting logic into a different function.

2024-08-15 12:04 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +    public function indexForWashingMachines()
Now, I could remove that separate route and solve it via the index route.

2024-08-25 17:31 UTC, viktorcsimma commented on resources/views/emails/reservation_requested.blade.php
> +    @endphp
It's only for here; I'll think it's going to be fine for now.

2024-08-29 12:19 UTC, viktorcsimma commented on app/Http/Controllers/ReservableItemController.php
> +            'type' => Rule::in(["washing_machine", "room"]),
Done:)

2024-08-29 12:21 UTC, viktorcsimma commented on app/Http/Controllers/ReservableItemController.php
> +    }
Done:)

2024-08-29 12:21 UTC, viktorcsimma commented on app/Http/Controllers/ReservableItemController.php
> +    }
Done:) I've solved it by queueing.

2024-08-29 12:22 UTC, viktorcsimma commented on app/Http/Controllers/ReservableItemController.php
> +    }
It will be fine for now.

2024-08-29 12:22 UTC, viktorcsimma commented on app/Http/Controllers/ReservableItemController.php
> +    }
It is not that important for now.

2024-08-29 12:25 UTC, viktorcsimma commented on app/Http/Controllers/ReservableItemController.php
> +    }
I cannot; I depend on the type in the Blade file.

2024-08-29 13:07 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +    }
Done:) I've reworked it so that it does not use the model itself, but an array.

2024-08-29 13:08 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +    }
Same here.

2024-08-29 13:09 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +    }
Nice catch:D

2024-08-29 13:10 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +    }
I don't understand; isn't your code the same as what I have already written?

2024-08-29 13:16 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +        }
I moved that logic into the 'modify' policy; thanks!

2024-08-29 13:19 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +        }
I've moved the first part to a policy; the second would not be worth a separate function IMO.

2024-08-29 13:24 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +        }
I think this is not worth a separate function... it is not a meaningful code block by itself.

2024-08-29 15:07 UTC, viktorcsimma commented on app/Http/Controllers/ReservationController.php
> +    }
OK; thank you:)

2024-08-29 15:54 UTC, viktorcsimma commented on app/Mail/ReservationDeleted.php
> +        );
Nice; I'll take this one:)

2024-08-29 15:56 UTC, viktorcsimma commented on app/Models/User.php
> +    }
We might do so.

2024-09-02 12:35 UTC, viktorcsimma commented on database/factories/EducationalInformationFactory.php
> +            'research_topics' => $this->faker->paragraph(rand(1, 3)),
This is a factory; we don't need a CSPRNG here.

2024-09-04 20:09 UTC, kdmnk commented
Hi! Sorry, I can take a quick look again tomorrow morning. I know you want to merge soon so we'll see

2024-09-04 20:21 UTC, viktorcsimma commented
@kdmnk thank you:)

2024-09-04 20:37 UTC, viktorcsimma commented on app/Http/Controllers/ReservableItemController.php
> +    }
This will be fine for now.

2024-09-05 07:41 UTC, kdmnk approved these changes
This is a crazy huge module, if everything works, good job!
Despite the approval, I left some comments, I hope you can take a look.

And one more thing: please put all related Models, Emails and Email blades into its own subdirectory as those are starting to be too many in a flat hierarchy.

Understanding the code might take some time, but let's see how many times do you have to come back here to fix or extend some functionality... Otherwise, it is quite separated from the rest of the system so I think it is fine.
I recommend to come back here some time later and try to improve the software architecture. It's not trivial but a nice example for improving that.

And about the receptionists: we had some issues some years ago with the fault reporting, that they do not have a computer there. I don't know if it is still a problem, but better to take a look and ensure that it is feasible for them to access the system. Otherwise, you could put a screen in the entrance hall showing the current status of the rooms. 

Good job again, it is a long awaited module, I hope it will be successful!

2024-09-05 07:41 UTC, kdmnk commented on app/Exceptions/ConflictException.php
> +class ConflictException extends \Exception
rename to resevation conflict exception

2024-09-05 07:41 UTC, kdmnk commented on app/Policies/ReservableItemPolicy.php
> +    public static function canRequestReservationForType(User $user, ReservableItemType $type): bool
you can make these non static and call them in the conventional way: authorize('canRequestReservationForType', [ReservableItem::class, $type]).

2024-09-05 07:41 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +    public function store(ReservableItem $item, Request $request)
Split this into multiple functions. For example (from chatgpt):

   ```
 $this->authorize('requestReservation', $item);

    if ($item->isWashingMachine() && self::reachedMaximumForWashingMachines(user())) {
        return redirect()->back()->with('error', __('reservations.max_washing_reservations_reached'));
    }

    $validatedData = $this->validateReservation($request, $item);

    if ($item->isRoom() && isset($request->recurring)) {
        return $this->handleRecurringReservation($validatedData, $item, $request);
    } else {
        return $this->handleSingleReservation($validatedData, $item);
    }
```

2024-09-05 07:41 UTC, kdmnk commented on app/Http/Controllers/ReservationController.php
> +    public function update(Reservation $reservation, Request $request)
Same, split this into multiple functions. If makes sense, you could create an interface and two more classes for handling washing machines and for rooms.

2024-09-05 07:41 UTC, kdmnk commented on app/Models/ReservationGroup.php
> +            foreach($allAfter as $reservation) {
foreach body is too long, should be a new private function

2024-09-05 12:31 UTC, viktorcsimma commented
Thank you so much:) I have applied almost all of the things you have suggested. I have not tried interfaces for ReservationController though; I think I will do so when redesigning the architecture later (which I should).

What do you think, can we proceed with the merge? I would try it on staging then.

2024-09-05 12:37 UTC, viktorcsimma commented on resources/views/emails/reservations/reservation_affected.php
> +    <h1>@lang('mail.dear') {{ $recipient }}!</h1>
Oh; I've forgotten the `.blade` from the name. Thanks:)

2024-09-05 12:47 UTC, viktorcsimma commented on app/Http/Controllers/Dormitory/Reservations/ReservationController.php
> +        return redirect()->route('reservations.items.show', $reservation->reservableItem);
Done:)

2024-09-05 12:48 UTC, viktorcsimma commented on app/Http/Controllers/Dormitory/Reservations/ReservationController.php
> +    }
Done:)

2024-09-05 12:52 UTC, viktorcsimma commented on app/Mail/Reservations/ReportReservableItemFault.php
> +    }
Done:)

2024-09-05 13:00 UTC, viktorcsimma commented on app/Http/Controllers/Dormitory/Reservations/ReservableItemController.php
> +        }
Done:)

2024-09-06 09:01 UTC, merged